<h2>Reading Data, Exploring Data Types, Properties and Basic Statistics in pandas</h2>

We import two of the most fundamental libraries for data mining: [pandas](https://pandas.pydata.org/docs/index.html) for data manipulation and [numpy](https://numpy.org/) for numerical computations.

In [ ]:
import pandas as pd
import numpy as np

# testing some things
# you sure bud?

print("testing some things")

---

### The `read_csv()` Function in pandas
We are using `pd.read_csv` to read two CSV files:
- `country_wise_latest.csv`: This contains the latest country-wise statistics for COVID-19.
<!-- - `day_wise.csv`: This file holds the day-wise statistics for global COVID-19 cases. -->

Parameters used:
- `pd.read_csv(file_path)`: Reads the CSV files from the specified path.
- `sep=','`: Specifies the separator used to divide values in the file. The default value is a comma (`,`), which is used in standard CSV files like ours.

Since commas are the default separator in `pd.read_csv()`, there is no need to specify this parameter unless a different separator is used (e.g., a tab `\t` or semicolon `;`).

In [ ]:
# Reading the CSV file
df1 = pd.read_csv('country_wise_latest.csv')

In [ ]:
# Load the second CSV file (covid_19_clean_complete.csv) into a different DataFrame - you will need it later on
df2 = pd.read_csv('covid_19_clean_complete.csv')
# <code here>

---

### The `head()` Function in pandas
The `head()` function in pandas allows you to preview the first few rows of a DataFrame. By default, it shows the first 5 rows, but you can specify a different number of rows if needed.

**Syntax**: `df.head(n)`  
- `n` (optional): The number of rows to display. If not specified, the default is 5.

This method is useful for quickly inspecting the top rows of a dataset to understand its structure and contents.

In [ ]:
# Display the first few rows of both dataset
df1.head()

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa

In [ ]:
# Do the same for the Covid dataset
df2.head()
# <code here>

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.94,67.71,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.15,20.17,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.03,1.66,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.51,1.52,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.20,17.87,2020-01-22,0,0,0,0,Africa

---

### The `tail()` Function in pandas

The `tail()` function in pandas allows you to view the last few rows of a DataFrame. By default, it returns the last 5 rows, but you can specify the number of rows to display.

#### Syntax:
`df.tail(n)`

- **n** (optional): The number of rows to return. If not specified, the default is 5.

This function is useful for quickly inspecting the final portion of a dataset.

In [ ]:
df1.tail()

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [ ]:
# Do the same for the Covid dataset
df2.tail()
# <code here>

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
49063,NaN,Sao Tome and Principe,0.19,6.61,2020-07-27,865,14,734,117,Africa
49064,NaN,Yemen,15.55,48.52,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,NaN,Comoros,-11.65,43.33,2020-07-27,354,7,328,19,Africa
49066,NaN,Tajikistan,38.86,71.28,2020-07-27,7235,60,6028,1147,Europe
49067,NaN,Lesotho,-29.61,28.23,2020-07-27,505,12,128,365,Africa

---

### The `shape` Attribute in pandas

The `shape` attribute in pandas returns a tuple representing the dimensions of a DataFrame. It provides two values:
- The number of rows.
- The number of columns.

This is useful for quickly inspecting the size and structure of the dataset.

In [ ]:
# Print the shape of the dataset
print(df1.shape)
print(df2.shape)
# <code here>

(187, 15)
(49068, 10)

---

### The `info()` Function in pandas
The `info()` function in pandas provides a concise summary of a DataFrame, including:
- The total number of entries (rows) and columns.
- The names of all the columns and their data types.
- The number of non-null values in each column.
- Memory usage of the DataFrame.

This method is useful for quickly inspecting the structure and contents of a DataFrame.

Example:
`df.info()`

In [ ]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country/Region          187 non-null    str
 1   Confirmed               187 non-null    int64
 2   Deaths                  187 non-null    int64
 3   Recovered               187 non-null    int64
 4   Active                  187 non-null    int64
 5   New cases               187 non-null    int64
 6   New deaths              187 non-null    int64
 7   New recovered           187 non-null    int64
 8   Deaths / 100 Cases      187 non-null    float64
 9   Recovered / 100 Cases   187 non-null    float64
 10  Deaths / 100 Recovered  187 non-null    float64
 11  Confirmed last week     187 non-null    int64
 12  1 week change           187 non-null    int64
 13  1 week % increase       187 non-null    float64
 14  WHO Region              187 non-null    str
dtypes: float64(4), int64(9), str(2)
memory usage: 22.0 KB

---

### The `type()` Function in pandas
The `type()` method in Python returns the type of a given object. It can be used to check the type of a variable, a DataFrame, or any other object.

For example:
- `type(df)` will return `<class 'pandas.core.frame.DataFrame'>`, confirming that `df` is a DataFrame.
- You can also use it on individual columns or any variable to determine their type.

Example:
`type(df['column_name'])`

In [ ]:
print(type(df1['WHO Region'][0]))
type(df1['Country/Region'][0])

<class 'str'>

str

### Why Does `type()` Return Different Outputs?

In Jupyter notebooks, the `type()` function may return different outputs depending on how it's used:

- **With `print()`**: The full class information is displayed, like `<class 'str'>`.
  - Example: `print(type(df1['WHO Region'][0]))` will output `<class 'str'>`.
  
- **Without `print()`**: Jupyter automatically simplifies the output to just `str`.
  - Example: `type(df1['Country/Region'][0])` will display `str`.

To ensure consistent results, always use `print()` to display the output of `type()`.

In [ ]:
# Print the type of at least 3 columns from the COVID dataset
for i in range(3):
    print(type(df2[df2.columns[i]][8]))
# <code here>

<class 'str'>
<class 'str'>
<class 'numpy.float64'>

---

### The `describe()` Function in pandas

The `describe()` function in pandas generates descriptive statistics for numerical columns of a DataFrame, providing a summary of key statistical measures.

#### Key Outputs:
- **count**: The number of non-null (valid) entries in the column.
- **mean**: The average (mean) value of the data in the column.
- **std**: The standard deviation, a measure of how spread out the data is.
- **min**: The minimum value in the column.
- **25% (1st Quartile)**: The value below which 25% of the data falls.
- **50% (Median)**: The middle value of the data.
- **75% (3rd Quartile)**: The value below which 75% of the data falls.
- **max**: The maximum value in the column.

In [ ]:
df1.describe()

/Users/nikolanikolov/Desktop/ML/.venv/lib/python3.14/site-packages/pandas/core/nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase
count,187.00,187.00,187.00,187.00,187.00,187.00,187.00,187.00,187.00,187.00,187.00,187.00,187.00
mean,88130.94,3497.52,50631.48,34001.94,1222.96,28.96,933.81,3.02,64.82,inf,78682.48,9448.46,13.61
std,383318.66,14100.00,190188.19,213326.17,5710.37,120.04,4197.72,3.45,26.29,NaN,338273.68,47491.13,24.51
min,10.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.00,-47.00,-3.84
25%,1114.00,18.50,626.50,141.50,4.00,0.00,0.00,0.94,48.77,1.45,1051.50,49.00,2.77
50%,5059.00,108.00,2815.00,1600.00,49.00,1.00,22.00,2.15,71.32,3.62,5020.00,432.00,6.89
75%,40460.50,734.00,22606.00,9149.00,419.50,6.00,221.00,3.88,86.89,6.44,37080.50,3172.00,16.86
max,4290259.00,148011.00,1846641.00,2816444.00,56336.00,1076.00,33728.00,28.56,100.00,inf,3834677.00,455582.00,226.32

### Explanation of `e+02` in `describe()`

The `e+02` notation seen in the `describe()` output refers to scientific notation, which is used to express very large or very small numbers in a compact form. 

In scientific notation, `e+02` means "multiply by \(10^2\)" (or 100). For example:
- `1.87e+02` is equivalent to `1.87 × 10^2 = 187`.
- `8.81e+04` is equivalent to `8.81 × 10^4 = 88,130`.

This notation is often used in pandas to make it easier to display large datasets in a more compact form, especially when numbers vary widely in magnitude.

---

### How to Bypass Scientific Notation

If you want to disable scientific notation and display the full numbers in pandas, you can adjust the pandas display settings using `pd.set_option()`. This allows you to format the output with a specific number of decimal places. 

For example:
```python
pd.set_option('display.float_format', '{:.2f}'.format)

The command `pd.set_option('display.float_format', '{:.2f}'.format)` modifies how floating-point numbers are displayed in pandas. It formats all floats to show 2 decimal places (`.2f`), ensuring consistent number presentation throughout the DataFrame without scientific notation.

In [ ]:
pd.set_option('display.float_format', '{:.2f}'.format)

---

In [ ]:
# Display the new description for both datasets (Country and Covid)
df1.describe()
df2.describe()
#????
# <code here>

/Users/nikolanikolov/Desktop/ML/.venv/lib/python3.14/site-packages/pandas/core/nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

           Lat     Long  Confirmed    Deaths  Recovered     Active
count 49068.00 49068.00   49068.00  49068.00   49068.00   49068.00
mean     21.43    23.53   16884.90    884.18    7915.71    8085.01
std      24.95    70.44  127300.21   6313.58   54800.92   76258.90
min     -51.80  -135.00       0.00      0.00       0.00     -14.00
25%       7.87   -15.31       4.00      0.00       0.00       0.00
50%      23.63    21.75     168.00      2.00      29.00      26.00
75%      41.20    80.77    1518.25     30.00     666.00     606.00
max      71.71   178.06 4290259.00 148011.00 1846641.00 2816444.00

### Explanation of `std (383318.66)` in the Confirmed Column

The **std (383318.66)** represents the **standard deviation** of the confirmed cases. It indicates the spread of the data around the mean. A high standard deviation means there is a wide range in the number of confirmed cases across locations/countries, with significant variation from the average.


### Explanation of Percentiles in the Confirmed Column

- **25% (1114.00)**:  
  This represents the **first quartile (Q1)**. It means that 25% of the locations/countries have confirmed cases **less than or equal to 1,114**, while 75% have more.

- **50% (5059.00)**:  
  This represents the **median (Q2)**, or the middle value of the dataset. Half of the locations/countries have confirmed cases **less than or equal to 5,059**, and the other half have more.

- **75% (40460.50)**:  
  This represents the **third quartile (Q3)**. It means that 75% of the locations/countries have confirmed cases **less than or equal to 40,460.50**, while 25% have more.

These percentiles help to understand how the confirmed cases are distributed across different locations/countries in the dataset.

---

### Mapping Statistics to Functions in pandas

When calculating basic statistics for a specific column in pandas, you can use the following functions:

- **Mean**: `<target_column>.mean()` — This calculates the average of the column.
- **Standard Deviation**: `<target_column>.std()` — This measures how much the values deviate from the mean.
- **Min**: `<target_column>.min()` — Returns the smallest value in the column.
- **Max**: `<target_column>.max()` — Returns the largest value in the column.
- **Quartiles**: 
  - **25th percentile (Q1)**: `<target_column>.quantile(0.25)` — The value below which 25% of the data falls.
  - **50th percentile (Median)**: `<target_column>.median()` or `<target_column>.quantile(0.50)` — The middle value of the data.
  - **75th percentile (Q3)**: `<target_column>.quantile(0.75)` — The value below which 75% of the data falls.

These functions allow you to compute individual statistics for any column in your dataset. For example, you can apply these to the **New recovered** column to explore its central tendencies and spread.

In [ ]:
# Display the summary statistics of the COVID dataset for the New Recovered cases column

# 1. Compute the statistics

mean_new_recovered = df2['Recovered'].mean()
std_new_recovered = df2['Recovered'].std()
min_new_recovered = df2['Recovered'].min()
max_new_recovered = df2['Recovered'].max()
q1_new_recovered = df2['Recovered'].quantile(0.25)
q2_new_recovered = df2['Recovered'].quantile(0.5)
q3_new_recovered = df2['Recovered'].quantile(0.75)

# 2. Display the results
print(f"Mean: {mean_new_recovered}")
print(f"Standard Deviation: {std_new_recovered}")
print(f"Minimum: {min_new_recovered}")
print(f"Maximum: {max_new_recovered}")
print(f"25% (Q1): {q1_new_recovered}")
print(f"50% (Median): {q2_new_recovered}")
print("75% (Q3): " + str(q3_new_recovered))

Mean: 7915.713479253282
Standard Deviation: 54800.91873054018
Minimum: 0
Maximum: 1846641
25% (Q1): 0.0
50% (Median): 29.0
75% (Q3): 666.0

### Difference Between `print(f"...")` and `print("..." + str(...))`

1. **`print(f"50% (Median): {q2_new_recovered}")`**:
   - This is **f-string** formatting, introduced in Python 3.6+. It allows you to directly embed variables within curly braces `{}` inside a string, making the code more concise and readable.

2. **`print("75% (Q3): " + str(q3_new_recovered))`**:
   - This uses string concatenation. The `str()` function converts the variable to a string before combining it with another string using the `+` operator.

---

### The `isnull()` Function in pandas

The `isnull()` function in pandas identifies missing (null or NaN) values in a DataFrame. It returns a DataFrame of the same shape, with `True` indicating missing values and `False` indicating non-missing values. This function is useful for detecting incomplete data, which is crucial for data cleaning and preprocessing. By understanding where data is missing, we can take appropriate steps, such as filling or removing those values, to ensure accurate analysis.

In [ ]:
# Using isnull() to detect missing values
missing_values = df1.isnull()

# Display the DataFrame with True for missing values and False for non-missing values
print(missing_values)

     Country/Region  Confirmed  Deaths  Recovered  Active  New cases  \
0             False      False   False      False   False      False
1             False      False   False      False   False      False
2             False      False   False      False   False      False
3             False      False   False      False   False      False
4             False      False   False      False   False      False
..              ...        ...     ...        ...     ...        ...
182           False      False   False      False   False      False
183           False      False   False      False   False      False
184           False      False   False      False   False      False
185           False      False   False      False   False      False
186           False      False   False      False   False      False

     New deaths  New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0         False          False               False                  False
1         False          False               False                  False
2         False          False               False                  False
3         False          False               False                  False
4         False          False               False                  False
..          ...            ...                 ...                    ...
182       False          False               False                  False
183       False          False               False                  False
184       False          False               False                  False
185       False          False               False                  False
186       False          False               False                  False

     Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                     False                False          False
1                     False                False          False
2                     False                False          False
3                     False                False          False
4                     False                False          False
..                      ...                  ...            ...
182                   False                False          False
183                   False                False          False
184                   False                False          False
185                   False                False          False
186                   False                False          False

     1 week % increase  WHO Region
0                False       False
1                False       False
2                False       False
3                False       False
4                False       False
..                 ...         ...
182              False       False
183              False       False
184              False       False
185              False       False
186              False       False

[187 rows x 15 columns]

### Output of `isnull()`

The `isnull()` function returns a DataFrame of the same shape, where each cell contains either `True` or `False`. 
- **`True`** indicates that the value in the corresponding cell is missing (null or NaN).
- **`False`** indicates that the value in the corresponding cell is not missing.

This allows us to identify which parts of the DataFrame have missing data, helping in the data cleaning process.
We can use it directly on a column too. For example:

In [ ]:
# Get the Dataframe with the missing values from the "Country/Region" column of the Country dataset
df1[df1['Country/Region'].isnull()]
# <code here>

Empty DataFrame
Columns: [Country/Region, Confirmed, Deaths, Recovered, Active, New cases, New deaths, New recovered, Deaths / 100 Cases, Recovered / 100 Cases, Deaths / 100 Recovered, Confirmed last week, 1 week change, 1 week % increase, WHO Region]
Index: []

### Output Explanation of `isnull()`

In this output, `isnull()` is applied to the **Country/Region** column, returning `True` for missing values and `False` for non-missing values. However, only the first few and last few rows are displayed, with the middle rows omitted (indicated by `...`). As a result, while we can see that the first and last rows contain no missing values, the state of the rows in between is not immediately visible from this output.

### How to Get the Count of Missing Values per Column

When using `isnull()`, it returns `True` or `False` for each cell, but it doesn't summarize how many missing values exist per column. To address this, we use `isnull().sum()` to get the total number of missing values for each column. This gives a clearer breakdown of missing data, helping us assess data quality and decide how to handle missing values for each column.

In [ ]:
# Count the number of missing values in each column
df1['Country/Region'].isnull().sum()
# <code here>

np.int64(0)

### Explanation of `df.isnull().sum()`

The command `df.isnull().sum()` checks for missing (null) values in the DataFrame `df`. 

- **`isnull()`**: Identifies whether each element is missing (`True` for missing, `False` for non-missing).
- **`sum()`**: Adds up the number of `True` values (which represent null values) for each column.

The result is the total count of missing values for each column in the DataFrame.

---

### The `duplicated()` Function in pandas

The `duplicated()` function in pandas identifies duplicate rows in a DataFrame or Series. It returns a boolean Series where:
- **`True`** indicates that the row is a duplicate (i.e., it has appeared before).
- **`False`** indicates that the row is unique.

By default, it checks for duplicates across all columns, but you can specify columns or control whether the first or last occurrence is marked as duplicate.

This function is useful for identifying and handling repeated data entries.

In [ ]:
# Find the duplicates in the Country dataset
print(df1.duplicated())
print(df2.duplicated())
# <code here>

0      False
1      False
2      False
3      False
4      False
       ...
182    False
183    False
184    False
185    False
186    False
Length: 187, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
49063    False
49064    False
49065    False
49066    False
49067    False
Length: 49068, dtype: bool

### Common Issue with `duplicated()` Output

Similar to `isnull()`, the `duplicated()` function returns a Series of `True` or `False` values for each row, indicating whether it's a duplicate. However, this output alone doesn't tell us how many duplicates are present in each column. To solve this, we can use `duplicated().sum()` to get the total count of duplicate rows in the dataset. This gives a clear summary of how many rows are duplicated.

In [ ]:
# Count the number of duplicate rows
print(df1.duplicated().sum())
print(df2.duplicated().sum())
# <code here>

### Explanation of `df1.duplicated().sum()`

Running `df1.duplicated().sum()` provides the total count of duplicated rows in the DataFrame. It identifies duplicate rows and then sums them to give the number of repeated entries, offering a quick overview of data redundancy in the dataset.